#? stage fot install dependencies for the app
FROM node:20-alpine AS deps
WORKDIR /deps

COPY package.json ./
RUN npm install

#? stage for run the app
FROM node:20-alpine AS runner
WORKDIR /app

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 discord

RUN apk add --no-cache libsodium ffmpeg

COPY --from=deps /deps/node_modules ./node_modules
COPY --from=deps /deps/package.json ./package.json
COPY . .

USER discord

CMD ["npm", "run", "dev"]